### ISSUE TITLE
review existing lint rules and verify best practices

### ISSUE THREAD

**Issue by obuckley-kenzan** [kenzanmedia/pipeline-validate-css#2]
@ayjee 
Can you please review the current lint rules and update if you see any thing that should be updated?

**Comment by ayjee** [comment]
@obuckley-kenzan, In my opinion many of these should be updated to true.  Basically the way it is set right now it will not lint much of anything.  @jpoo90 and I had an initial conversation about this but we didn't get to review any of the rules together.  I wasn't sure if we intended to leave all the customization to the user here and that was why the rules were set to false.  I can submit a PR if you would like?

cc: @jpoo90

**Comment by obuckley-kenzan** [comment]
Thanks for reviewing @ayjee .

The current plan is to bundle our best practices version of a `.csslintrc` file with the pipeline, but allow the user to provide their own if they want to override our defaults.

So whatever you think the setting is for each rule, please feel free to submit a PR with those changes.

**Comment by jpoo90** [comment]
@ayjee Yes all of the rules are off now because I wanted to talk with you to decide which of those were appropriate. The idea is to have our opinionated rules in the `.csslintrc` of this pipeline, setting a quality validation. If you can submit a PR activating the rules you consider are necessary that would be great.

**Comment by ayjee** [comment]
sure thing @obuckley-kenzan / @jpoo90.  I will take a look a submit a PR.
